version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-bankmark
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-bankmark-data:/var/lib/grafana
    networks:
      - grafana-network
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb-bankmark
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_DB=evidently_metrics
    volumes:
      - influxdb-bankmark-data:/var/lib/influxdb
    networks:
      - grafana-network

volumes:
  grafana-bankmark-data:
    driver: local
  influxdb-bankmark-data:
    driver: local

networks:
  grafana-network:
    driver: bridge